"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getSheetTabIds = void 0;
const google_spreadsheet_1 = require("google-spreadsheet");
const getSheetTabIds = async (sheetId) => {
    console.log("*** getSheetTabIds 👎");
    // be be replaced by auth.json data
    const { GOOGLE_SERVICE_ACCOUNT_EMAIL, GOOGLE_PRIVATE_KEY } = process.env;
    if (GOOGLE_SERVICE_ACCOUNT_EMAIL && GOOGLE_PRIVATE_KEY && sheetId) {
        const doc = new google_spreadsheet_1.GoogleSpreadsheet(sheetId);
        await doc.useServiceAccountAuth({
            // env var values are copied from service account credentials generated by google
            // see "Authentication" section in docs for more info
            client_email: GOOGLE_SERVICE_ACCOUNT_EMAIL,
            private_key: GOOGLE_PRIVATE_KEY,
        });
        await doc.loadInfo(); // loads document properties and worksheets
        return doc.sheetsByIndex.map((tab) => ({
            sheetId: tab.sheetId,
            sheetName: tab.title,
        }));
    }
    return [];
};
exports.getSheetTabIds = getSheetTabIds;
